// Resolves the optimized image derivatives (generated by scripts/optimize-media.mjs)
// into hashed, build-time URLs and groups them into srcset-ready sets per source image.
//
// Each set: { avif, webp, jpg } srcSet strings ("<url> 800w, <url> 1600w") plus
// `src` (the 1600w JPEG fallback). Pass the result to <ResponsiveImage image={...} />.

const modules = import.meta.glob('../assets/images/optimized/*.{avif,webp,jpg}', {
  eager: true,
  query: '?url',
  import: 'default',
});

// base name -> { avif: {800,1600}, webp: {...}, jpg: {...} }
const byBase = {};
for (const [path, url] of Object.entries(modules)) {
  const m = path.match(/\/([^/]+)-(800|1600)\.(avif|webp|jpg)$/);
  if (!m) continue;
  const [, base, width, ext] = m;
  (byBase[base] ??= { avif: {}, webp: {}, jpg: {} })[ext][width] = url;
}

const srcset = (fmt) => `${fmt['800']} 800w, ${fmt['1600']} 1600w`;

/** Build a responsive image set for the given optimized base filename. */
export function imageSet(base) {
  const set = byBase[base];
  if (!set) throw new Error(`No optimized derivatives found for "${base}"`);
  return {
    avif: srcset(set.avif),
    webp: srcset(set.webp),
    jpg: srcset(set.jpg),
    src: set.jpg['1600'],
  };
}
